services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/jmurth-site
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: